---
- name: Install server packages
  apt:
    cache_valid_time: 86400
    install_recommends: no
    update_cache: True
    state: present
    name: '{{ item }}' 
  with_items: '{{ rsyslog_packages.server[ansible_distribution][ansible_distribution_major_version] }}'

- name: Force server client_address to 127.0.0.1
  set_fact:
    client_address: 127.0.0.1

- name: Generate config file
  template:
    src: syslog_server.conf.j2
    dest: /etc/rsyslog.d/49central-server.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart rsyslog
